# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Degree Art Blog"
description: > # this means to ignore newlines until "email:"
   An art blog for keeping degree work

email: 230030092@student.hca.ac.uk
#blog logo
logo: "/assets/images/blog_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/BLOGPHOTOS/touchgrass.jpg"

name: 'Ethan Riley'
author: 'Ethan Riley'
author_image: "/assets/images/blog_logo.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: youtube	
    url:	https://www.youtube.com/@uniquehue
    desc: subscribe to my youtube channel
    share_url: 
    share_title: 
    share_link: 

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/UnkDevE
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: instagram
    url: https://www.instagram.com/hermit_calligrapher/
    desc: follow me on instagram
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
